export type DomainErrorCode =
  | "EmptyEventStream"
  | "EmptyEventBatch"
  | "InvalidDomainBatchSemantics"
  | "EventGameMismatch"
  | "EventSequenceJump"
  | "EventGameVersionMismatch"
  | "EventBatchMismatch"
  | "EventCommandMismatch"
  | "EventRulesBaselineMismatch"
  | "DuplicateEventId"
  | "DuplicateCommandBatch"
  | "NonContiguousBatch"
  | "DuplicateGameCreated"
  | "MissingGameCreated"
  | "UnsupportedEventVersion"
  | "InvalidPlayerCounts"
  | "InvalidGameCreatedPayload"
  | "InvalidScriptSelectedPayload"
  | "InvalidScriptSelectedPhase"
  | "DuplicateScriptSelected"
  | "InvalidSeamstressResolutionCapabilityDeclaredPayload"
  | "DuplicateSeamstressResolutionCapabilityDeclared"
  | "InvalidSetupGeneratedPayload"
  | "DuplicateSetupGenerated"
  | "InvalidPlayerRosterCreatedPayload"
  | "DuplicatePlayerRosterCreated"
  | "InvalidCharactersAssignedPayload"
  | "DuplicateCharactersAssigned"
  | "InvalidFirstNightInitializedPayload"
  | "DuplicateFirstNightInitialized"
  | "InvalidInitialPrivateKnowledgeEstablishedPayload"
  | "DuplicateInitialPrivateKnowledgeEstablished"
  | "InvalidFirstNightTaskPlanCreatedPayload"
  | "DuplicateFirstNightTaskPlanCreated"
  | "InvalidFirstNightActionOpportunityCreatedPayload"
  | "InvalidPhilosopherActionDeferredPayload"
  | "InvalidSeamstressActionDeferredPayload"
  | "InvalidSeamstressTargetsChosenPayload"
  | "InvalidSeamstressAbilitySpentPayload"
  | "InvalidSeamstressInformationDeliveredPayload"
  | "InvalidRoleTenureId"
  | "InvalidRoleTenureState"
  | "InvalidRoleTenureTransitionFact"
  | "InvalidSeamstressAbilityInstanceId"
  | "InvalidSeamstressAbilityUseEntitlementId"
  | "InvalidSeamstressTarget"
  | "AbilityUseEntitlementAlreadySpent"
  | "InvalidPhilosopherAbilityChosenPayload"
  | "InvalidPhilosopherAbilityGrantedPayload"
  | "InvalidAbilityImpairmentAppliedPayload"
  | "InvalidFirstNightTaskInsertedPayload"
  | "InvalidFirstNightTaskInsertedV2Payload"
  | "InvalidSnakeCharmerTargetChosenPayload"
  | "InvalidSnakeCharmerNoSwapResolvedPayload"
  | "InvalidSnakeCharmerIneffectiveResolvedPayload"
  | "InvalidSnakeCharmerDemonSwapAppliedPayload"
  | "InvalidWitchTargetChosenPayload"
  | "InvalidWitchDeathPendingMarkedPayload"
  | "InvalidWitchIneffectiveResolvedPayload"
  | "InvalidCerenovusChoiceRecordedPayload"
  | "InvalidCerenovusMadnessMarkedPayload"
  | "InvalidCerenovusMadnessInstructionDeliveredPayload"
  | "InvalidDreamerTargetChosenPayload"
  | "InvalidDreamerInformationDeliveredPayload"
  | "InvalidClockmakerInformationDeliveredPayload"
  | "InvalidMathematicianInformationDeliveredPayload"
  | "UnsupportedLegacyV1MathematicianReplay"
  | "InvalidEvilTwinPairEstablishedPayload"
  | "DuplicateEvilTwinPairEstablished"
  | "InvalidEvilTwinInformationDeliveredPayload"
  | "DuplicateEvilTwinInformationDelivered"
  | "InvalidMinionInformationDeliveredPayload"
  | "DuplicateMinionInformationDelivered"
  | "InvalidDemonInformationDeliveredPayload"
  | "DuplicateDemonInformationDelivered"
  | "InvalidScheduledTaskSettledPayload"
  | "PrivateKnowledgeUnavailable"
  | "UnknownPlayerPrivateKnowledgeViewer"
  | "InvalidPhaseTransition"
  | "InvalidPhaseTransitionReason"
  | "InvalidPhaseCounter"
  | "MissingTransitionPrerequisite"
  | "PhaseTransitionNotIntegrated"
  | "InvalidFirstNightAbilityOutcomeLedger"
  | "InvalidFirstNightAbilityOutcomeFact"
  | "InvalidFirstNightAbilityOutcomeWindow"
  | "InvalidFirstNightAbilityInstance"
  | "InvalidFirstNightAbilityOutcomeEvidence"
  | "DuplicateFirstNightAbilityOutcomeFactConflict";

export class DomainError extends Error {
  public constructor(
    public readonly code: DomainErrorCode,
    message: string
  ) {
    super(message);
    this.name = "DomainError";
  }
}

export const assertNever = (_value: never): never => {
  void _value;
  throw new DomainError("UnsupportedEventVersion", "Unexpected value");
};
